export const id = 'userAccess';

export const HANDLE_ADD_VALUE_SAGA = `${id}/HANDLE_ADD_VALUE_SAGA`;
export const HANDLE_ADD_VALUE_SAGA_STARTED = `${id}/HANDLE_ADD_VALUE_SAGA_STARTED`;
export const HANDLE_ADD_VALUE_SAGA_FINISHED = `${id}/HANDLE_ADD_VALUE_SAGA_FINISHED`;
export const HANDLE_ADD_VALUE_SAGA_ERROR = `${id}/HANDLE_ADD_VALUE_SAGA_ERROR`;

export const HANDLE_SUBSTRACT_VALUE_SAGA = `${id}/HANDLE_SUBSTRACT_VALUE_SAGA`;
export const HANDLE_SUBSTRACT_VALUE_SAGA_STARTED = `${id}/HANDLE_SUBSTRACT_VALUE_SAGA_STARTED`;
export const HANDLE_SUBSTRACT_VALUE_SAGA_FINISHED = `${id}/HANDLE_SUBSTRACT_VALUE_SAGA_FINISHED`;
export const HANDLE_SUBSTRACT_VALUE_SAGA_ERROR = `${id}/HANDLE_SUBSTRACT_VALUE_SAGA_ERROR`;

export const HANDLE_UPDATE_VALUE_REDUCER = `${id}/HANDLE_UPDATE_VALUE_REDUCER`;
