export const id = 'permissions';

export const HANDLE_CHANGE_BLUETOOTH_STATUS_SAGA = `${id}/HANDLE_CHANGE_BLUETOOTH_STATUS_SAGA`;
export const HANDLE_CHANGE_LOCATION_STATUS_SAGA = `${id}/HANDLE_CHANGE_LOCATION_STATUS_SAGA`;

export const HANDLE_CHANGE_BLUETOOTH_STATUS_REDUCER = `${id}/HANDLE_CHANGE_BLUETOOTH_STATUS_REDUCER`;
export const HANDLE_CHANGE_LOCATION_STATUS_REDUCER = `${id}/HANDLE_CHANGE_LOCATION_STATUS_REDUCER`;
