export const id = 'loader';

export const HANDLE_SHOW_LOADER_SAGA = `${id}/HANDLE_SHOW_LOADER_SAGA`;
export const HANDLE_HIDE_LOADER_SAGA = `${id}/HANDLE_HIDE_LOADER_SAGA`;

export const HANDLE_SHOW_LOADER_REDUCER = `${id}/HANDLE_SHOW_LOADER_REDUCER`;
export const HANDLE_HIDE_LOADER_REDUCER = `${id}/HANDLE_HIDE_LOADER_REDUCER`;
