export const id = 'app';

export const HANDLE_INITIALIZE_SAGA = `${id}/HANDLE_INITIALIZE_SAGA`;
export const HANDLE_INITIALIZE_SAGA_STARTED = `${id}/HANDLE_INITIALIZE_SAGA_STARTED`;
export const HANDLE_INITIALIZE_SAGA_FINISHED = `${id}/HANDLE_INITIALIZE_SAGA_FINISHED`;
export const HANDLE_INITIALIZE_SAGA_ERROR = `${id}/HANDLE_INITIALIZE_SAGA_ERROR`;
export const HANDLE_LOADING_REDUCER = `${id}/HANDLE_LOADING_REDUCER`;
